id: P000175
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །དོ་ཧ་སྐོར་གསུམ་གྱི་ཚིག་དོན་གྱི་རྣམ་བཤད་སེམས་ཀྱི་རྣམ་ཐར་གསལ་བར་སྟོན་པའི་མེ་ལོང་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - རྩ་བ་མཛད་པ་པོ། གྲུབ་ཆེན་ས་ར་ཧ།
  - འགྲེལ་པ་མཛད་པ་པོ། རྗེ་ཀརྨ་ཕྲིན་ལས།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  - yigchung
  id: VVI-006
web_metadata:
  title:
    en: Commentaries on Saraha’s Three Cycles of Dohas, the Spiritual Songs
    bo: ས་ར་ཧའི་དོ་ཧ་སྐོར་གསུམ།
  collection:
    en: Vajra Vidya Institute Library–  Book 6
    bo: བཛྲ་བིདྱཱ་དཔེ་མཛོད་ཁང་།–  དེབ། ༦
  author:
    en: Authors:Karma Thinleypa,Saraha
    bo: ཀརྨ་ཕྲིན་ལས་པ།,ས་ར་ཧ།
  pusblisher:
    en: Vajra Vidya Institute
    bo: བཛྲ་བིདྱཱ་གཙུག་ལག་སློབ་གཉེར་ཁང་།
  sku: VVI-006
  category:
    en: Spiritual Songs
    bo: མགུར།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: VVI-006.epub
  description:
    en: ༄༅། །དོ་ཧ་སྐོར་གསུམ་གྱི་ཊཱི་ཀ་འབྲིང་པོ་འདི་ནི་ཙཱ་རི་ཏྲ་ཡེ་ཤེས་ཀྱི་འཁོར་ལོའི་གནས་ཀྱི་བྱེ་བྲག་ཅིག་ཅར་གྱི་གནས་ཆེན་མཛེས་པའི་རྒྱན་དམ་པ་མཁས་ཤིང་དངོས་གྲུབ་ཀྱིས་བརྒྱན་པའི་རྡོར་འཛིན་ཆེན་པོ་བསྟན་པ་རྒྱ་མཚོ་བས་གསེར་གྱི་མེ་ཏོག་རས་དཀར་པོའི་ཅོད་པན་དང་བཅས་པ་ཡང་ཡང་སྩལ་ཏེ་ནན་ཏན་གྱིས་བསྐུལ་བའི་བཞེད་པ་བསྐོང་བ་དང་།
      ཉམས་རྟོགས་ཀྱི་རྒྱན་ལྡན་རི་ཁྲོད་དབང་ཕྱུག་མང་པོ་དང་གསུང་རབ་རབ་འབྱམས་སྨྲ་བའི་བཤེས་གཉེན་དུ་མས་བསྐུལ་བའི་ངོར་དགེ་སློང་ཆོས་སྨྲ་བ་ཀརྨ་ཕྲིན་ལས་པ་མིང་དངོས་དཔལ་ཕྱོགས་ཐམས་ཅད་ལས་རྣམ་པར་རྒྱལ་བའི་ལྷ་ཞེས་བྱ་བས་དཀར་པོའི་ལོ་ལ་ཡོལ་གཟིགས་ཁང་དུ་དབུ་གཙུགས་ཏེ།
      མཁས་གྲུབ་མང་པོའི་འབྱུང་གནས་ལེགས་བཤད་གླིང་གི་གཙུག་ལག་ཁང་དུ་ཡོངས་སུ་རྫོགས་པར་སྦྱར་བའོ།
      །
    bo: ༄༅། །དོ་ཧ་སྐོར་གསུམ་གྱི་ཊཱི་ཀ་འབྲིང་པོ་འདི་ནི་ཙཱ་རི་ཏྲ་ཡེ་ཤེས་ཀྱི་འཁོར་ལོའི་གནས་ཀྱི་བྱེ་བྲག་ཅིག་ཅར་གྱི་གནས་ཆེན་མཛེས་པའི་རྒྱན་དམ་པ་མཁས་ཤིང་དངོས་གྲུབ་ཀྱིས་བརྒྱན་པའི་རྡོར་འཛིན་ཆེན་པོ་བསྟན་པ་རྒྱ་མཚོ་བས་གསེར་གྱི་མེ་ཏོག་རས་དཀར་པོའི་ཅོད་པན་དང་བཅས་པ་ཡང་ཡང་སྩལ་ཏེ་ནན་ཏན་གྱིས་བསྐུལ་བའི་བཞེད་པ་བསྐོང་བ་དང་།
      ཉམས་རྟོགས་ཀྱི་རྒྱན་ལྡན་རི་ཁྲོད་དབང་ཕྱུག་མང་པོ་དང་གསུང་རབ་རབ་འབྱམས་སྨྲ་བའི་བཤེས་གཉེན་དུ་མས་བསྐུལ་བའི་ངོར་དགེ་སློང་ཆོས་སྨྲ་བ་ཀརྨ་ཕྲིན་ལས་པ་མིང་དངོས་དཔལ་ཕྱོགས་ཐམས་ཅད་ལས་རྣམ་པར་རྒྱལ་བའི་ལྷ་ཞེས་བྱ་བས་དཀར་པོའི་ལོ་ལ་ཡོལ་གཟིགས་ཁང་དུ་དབུ་གཙུགས་ཏེ།
      མཁས་གྲུབ་མང་པོའི་འབྱུང་གནས་ལེགས་བཤད་གླིང་གི་གཙུག་ལག་ཁང་དུ་ཡོངས་སུ་རྫོགས་པར་སྦྱར་བའོ།
      །
